### ISSUE TITLE
0xe2d3A739EFFCd3A99387d015E260eEFAc72EBea1

### ISSUE THREAD

**Issue by Nasralflahy** [dypfinance/Buyback-Farm-Stake-Governance-V2#3]

**Comment by Rambonner** [comment]
> _No description provided._

**Comment by Rambonner** [comment]
@doyledyp #
Duplicate of #
@`[2315-cleanup]
![Screenshot_20211226-141114_Samsung Internet](https://user-images.githubusercontent.com/96683179/147411683-4375c656-5349-45fc-ab0d-3e0b1f1d1347.jpg)
(https://github.com/ethereum/EIPs/pull/4331#pullrequestreview)`
